version: '3.4'

services:
  postgres:
    image: postgres:14
    ports:
      - "5435:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
